name: hello_world
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: erlangxk <simon.xikun@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  rxdart: ^0.22.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
