name: hello_world
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: erlangxk <simon.xikun@gmail.com>

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^1.2.2
  pedantic: ^1.0.0
  test: ^1.5.3
